### ISSUE TITLE
Problem With Paths In Windows

### ISSUE THREAD

**Issue by drorgl** [JacquesLucke/gcov-viewer#11]
Hi,
In my current setup the stored path does not have a full path, i.e, from vscode root folder it shows lib\test.cpp instead of c:\root\lib\test.cpp which causes an issue with [`findCachedDataForFile`](https://github.com/JacquesLucke/gcov-viewer/blob/master/src/extension.ts#L262)

I've worked around the problem by changing the condition but I'm sure it can cause issues and the storedPath should contain the full path rather than this quick workaround.
```
if (((storedPath.toLowerCase() === absolutePathWin) || (absolutePathWin.endsWith(storedPath.toLowerCase())))  && dataOfFile !== undefined) {
	return dataOfFile;
}
```

Am I configuring it in a wrong way?
My environment is PlatformIO, Mingw64, VSCode insiders.

**Comment by JacquesLucke** [comment]
I don't know much about how this works on windows tbh. Maybe @xiaoyun94 (who added windows support in #3) has some more information.

In general, I'd be fine with adding this "weaker" test if all the other methods don't find anything. Alternatively, if all files have a relative path from the same base path, we could ask the user to specify the base path or try to detect it automatically using some heuristic.

**Comment by drorgl** [comment]
Another way to do it perhaps is to use the `current_working_directory` from gcov output, which can then be concatenated to each `file` and `data_file` - this should produce a full path in Windows.

```json
{
    "gcc_version": "11.2.0",
    "files": [
        {
            "lines": [
                {
                    "branches": [],
                    "count": 0,
                    "line_number": 7,
                    "unexecuted_block": true,
                    "function_name": "output_start"
                }
                ...
                
            ],
            "functions": [
                {
                    "blocks": 2,
                    "end_column": 1,
                    "start_line": 7,
                    "name": "output_start",
                    "blocks_executed": 0,
                    "execution_count": 0,
                    "demangled_name": "output_start",
                    "start_column": 6,
                    "end_line": 13
                }
                ...
            ],
            "file": "test/temp.cpp"
        },
        ...
    ],
    "format_version": "1",
    "current_working_directory": "D:\nSoftware\nProject1",
    "data_file": ".pio/build/native/test/temp.gcda"
}
```

Do you have an example how it looks like in linux and mac?

**Comment by JacquesLucke** [comment]
This is how the output looks for me on linux: https://developer.blender.org/P2305.

**Comment by drorgl** [comment]
I've found a working solution, in Windows you need to add to gcc command `-fprofile-abs-path` for it to store the full paths in the gcda files.

**Comment by JacquesLucke** [comment]
Thanks for the update. I added this information to the readme.
