### ISSUE TITLE
Enable Gcov Binary path configuration in Workspace settings

### ISSUE THREAD

**Issue by ayoubsvbri** [JacquesLucke/gcov-viewer#27]
Hello,

Would it possible to allow the configuration of Gcov Binary location in workspace settings? 

Context:
I have a repository with .vscode workspace meant to be shared across developers. I would like to add Gcov Viewer's configuration to it so that it can point to a gcov binary in a container.

Thank you

**Comment by JacquesLucke** [comment]
Sounds reasonable. Not sure when I'll get to it. But maybe you can already try implementing this change yourself to see if it solves your use-case? 

It would probably involve changing this line: 
https://github.com/JacquesLucke/gcov-viewer/blob/master/package.json#L98

and maybe this one: 
https://github.com/JacquesLucke/gcov-viewer/blob/master/src/gcovInterface.ts#L36

**Comment by ayoubsvbri** [comment]
The fix was pretty straightforward and related to the first line you pointed out.
I'll let you review the changes waiting for a next release to benefit from it.

**Comment by JacquesLucke** [comment]
Thanks, LGTM

**Comment by JacquesLucke** [comment]
Just published the new version already.
